### ISSUE TITLE
Jung Extensions Dendrogram

### ISSUE THREAD

**Issue by njss** [stuarthendren/Jung-Extensions#5]
Hello,

I just found your jung-extensions library.
1) I am using the latest netbeans install, I've opened the project and tried to compile
1.a) I got errors like:
error: malformed HTML
- For the graph G(V, E) the induced graph of W < V is the subgraph G(W, F) where F < E and e in E is in F if and only

and

PartitionImpl.java:34: error: @param name not found
- @param graph

2) Can you provide me an example on how to create a dendrogram using your library?

Thank you so much in advance!
Nelson

**Comment by stuarthendren** [comment]
Hi Nelson

There are two implementations of the Dendrogram based on the way you want to build the data structure. 

One assumes you know each layer in full, in turn. And you can build the structure one partition at a time:
To create the partitions:

```
Partition<Character> partition = new PartitionImpl<Character>(graph.getEdges());
partition.addCluster('a', 'b');
partition.addCluster('c');
partition.addCluster('d', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm');
```

and to build the dendrogram

```
PartitionDendrogramImpl<Character> dendrogram = new PartitionDendrogramImpl<Character>();
dendrogram.addPartition(partition1);
dendrogram.addPartition(partition2);
```

The other implementation is needed for the situation where you don't build the dendrogram in a linear fashion but describe it as a graph (or tree). The tree has a root node and set of leaf nodes. Each node in the tree has a parent (except the root node) and each has a set of children (except the leaf nodes). 

You build the dendrogram by merging paths (or branches). You can describe a path by leaf node it ends at. I use a key and comparator to define the level of the dendrogram to make the merge. eg 

```
dendrogram.merge(1, 'a', 'b');
dendrogram.merge(2, 'b', 'c');
```

Here the 'a' and 'b' branches are merged together and then the 'c' gets merged above.

```
   /  \
  /     \
 /  \    |
 |   |   |
'a' 'b' 'c'
```

I have corrected the javadoc - if you spot any more feel free to do a pull request ;)

Stuart
